package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"backend_go/graph/model"
	"backend_go/internal/database"
	"context"
	"fmt"
)

// Artists is the resolver for the artists field.
func (r *queryResolver) Artists(ctx context.Context) ([]model.Artist, error) {
	panic(fmt.Errorf("not implemented: Artists - artists"))
}

// Songs is the resolver for the songs field.
func (r *queryResolver) Songs(ctx context.Context) ([]model.Song, error) {
	panic(fmt.Errorf("not implemented: Songs - songs"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver {
	db, err := database.NewDB(database.JSON)
	return &queryResolver{
		r,
		db
	}
}

type queryResolver struct {
	*Resolver
	db database.Database
}
