// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Age      int    `json:"age"`
	Email    string `json:"email"`
	NumViews int    `json:"num_views"`
}

type Query struct {
}

type Song struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	ArtistID string `json:"artist_id"`
	Length   int    `json:"length"`
}
